### ISSUE TITLE
#define serialSound error on MK3 remote

### ISSUE THREAD

**Issue by AJ292** [jlvandusen/JoesDriveSHADOW#2]
Hello again!

If I uncomment #define serialSound (as I want to run the soundboard into serial 3 of my Arduino), I get this error:

```MK3_Remote09.29.2022:256:8: error: redefinition of 'struct SEND_DATA_STRUCTURE'
 struct SEND_DATA_STRUCTURE{
        ^~~~~~~~~~~~~~~~~~~
/Users/aj/Desktop/JoesDriveSHADOW-master/MK3_Remote09.29.2022/MK3_Remote09.29.2022.ino:222:10: note: previous definition of 'struct SEND_DATA_STRUCTURE'
   struct SEND_DATA_STRUCTURE{
          ^~~~~~~~~~~~~~~~~~~
MK3_Remote09.29.2022:281:2: error: conflicting declaration 'int sendToBody'
 }sendToBody;
  ^~~~~~~~~~
/Users/aj/Desktop/JoesDriveSHADOW-master/MK3_Remote09.29.2022/MK3_Remote09.29.2022.ino:252:4: note: previous declaration as 'SEND_DATA_STRUCTURE sendToBody'
   }sendToBody;
    ^~~~~~~~~~
exit status 1
redefinition of 'struct SEND_DATA_STRUCTURE'
```

Very much appreciating the help and assistance so far - I'm getting very close to finishing off my first BB-8 build!

**Comment by jlvandusen** [comment]
Ok removed some redundant calls - I could not compile without effecting my ESP32 environment so give it a shot now
updated the version to 10/1/2022

**Comment by AJ292** [comment]
Will do - I'm just rewiring the sound board now. Will let you know how it goes.

**Comment by jlvandusen** [comment]
@AJ292 - I may start converting this completely to ESP32 with a custom board now that we have a working prototype for Joe's new V2 drive under beta currently.

**Comment by AJ292** [comment]
Interesting. How big of a departure is the new drive from MK3?

Also, the new code works - debug returns this:
```
SHADOW Bluetooth Library Started
SFX board found and configured in Uart mode
```

This is probably the wrong place to ask this, but I'm a bit lost as to what the next step is from here. I've put the MAC address of the primary PS3 Nav controller into the code, but nothing happens if I try to power on the controller.

**Comment by jlvandusen** [comment]
Send me a quick line at jlvandusen@msn.com

**Comment by AJ292** [comment]
Done. I'll close this bug - cheers!
